pipelines:
  - name: test_webhook
    steps:
      - name: my_action
        type: Bash
        configuration:
          inputResources:
            - name: open_pr 
        execution:
          onStart:
            - echo onStart
          onExecute:
            - echo "$res_open_pr_payload" | jq '.' > payload.json
            - cat payload.json
#            - read_json payload.json "LESSER_SECRET_FORMULA"
